import type { Metadata } from "next";
import RootLayoutClient from "./layout-client";
import Nav from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RootLayoutClient>
      <Nav />
      {children}
    </RootLayoutClient>
  );
}
